### ISSUE TITLE
Repo is empty

### ISSUE THREAD

**Issue by andrei-advisa** [Avira/prayas#1]
Hi guys! 
Found a link to that repo in your recent paper on A/B testing https://arxiv.org/pdf/2003.02769.pdf

You probably forgot to put the code in. I would really appreciate if you can share your experience with Bayesian A/B testing. 

Thanks,
Andrei from Advisa, Stockholm

**Comment by mjaeugster-avira** [comment]
Hi Andrei!

Thanks for your message -- great that you are interested in our AB framework. We are currently doing the remaining small bits&pieces to make the code releasable (writing documentation, cleaning up, etc.)

We will release the code at latest on 12.5., as the next day the IDSC conference happens where we present the paper (and the code, https://idsc.at/). We will write another comment here once the code is available.

Best,
Manuel.

**Comment by andrei-advisa** [comment]
Great, no rush! 
Looking forward to see what you're up to!

**Comment by mjaeugster-avira** [comment]
Hi Andrei -- the code, example notebooks, etc. is now available. Have fun and happy to hear your feedback!

**Comment by andrei-advisa** [comment]
Amazing, thanks! Happy to hear that!
